### ISSUE TITLE
Infografia sobre los Hilos

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/infografia-de-hilos-Ariadnamonserrat10#2]
[Infografia sobre los hilos (2).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Ariadnamonserrat10/files/15130878/Infografia.sobre.los.hilos.2.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rúbrica, has obtenido un 20% de 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
